---
abstract: 'Extract delimited text sequences from strings'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '1.001006'
configure_requires:
  Module::Build: '0.421'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Balanced-Marpa
provides:
  Text::Balanced::Marpa:
    file: lib/Text/Balanced/Marpa.pm
    version: '1.00'
requires:
  Const::Exporter: v0.2.3
  Marpa::R2: '2.096'
  Moo: '1.006'
  Tree: '1.05'
  Try::Tiny: '0.09'
  Types::Standard: '1.000004'
  open: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/ronsavage/Text-Balanced-Marpa
version: '1.00'
